# Use base image with GPU support.
FROM nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04

ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONUNBUFFERED=1

RUN apt-get update -y && apt-get install python3 python3-pip -y

WORKDIR /app
RUN python3 -m pip install tensorflow==2.11.0
RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y

COPY ./requirements.txt /app
RUN python3 -m pip install -r requirements.txt

COPY . .

ENTRYPOINT python3 Services/Inference/main.py --memory-limit 2048