apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: kserve-cloud-crop
  annotations:
    serving.kserve.io/enable-prometheus-scraping: "true"
spec:
  predictor:
    tolerations:
      - effect: NoSchedule
        key: feature.node.kubernetes.io/type
        operator: Equal
        value: gpu
    containers:
      - name: kserve-cloud
        image: akara4ok/kserve-cloud:latest
        command:
          - "python3"
          - "Services/KServe/KServeCrop.py"
        ports:
          - name: http1
            containerPort: 8080
            protocol: TCP
        env:
          - name: "APP_PORT"
            value: "8080"
        resources:
          limits:
            nvidia.com/gpu: 1
            memory: "8Gi"
            cpu: "2"
          requests:
            nvidia.com/gpu: 1
            memory: "8Gi"
            cpu: "2"
