export const UserRoutes = Object.freeze({
    GET_DATASETS: '/user/datasets/',
    CREATE_DATASET: '/dataset/',
    DELETE_DATASET: '/dataset/:id',
    GET_PROJECTS: '/user/projects/',
    GET_PROJECT_INFO: '/user/project/:id',
    GET_PROJECT_KEY: '/user/project/key/:id',
    CREATE_PROJECT: '/project/',
    LOAD_PROJECT: '/project/load/:id',
    STOP_PROJECT: '/project/stop/:id',
    PROJECT_LOGS: '/project/logs/:id',
    PROJECT_STATS: '/project/stats/:id',
    DELETE_PROJECT: '/project/:id',
    GET_CURRENT_USER: '/user/me',
    UPDATE_CURERENT_USER: '/user/me',
});