FROM akara4ok/base-image

WORKDIR /app

COPY ./requirements.txt /app
RUN python3 -m pip install -r requirements.txt

COPY ./OneClassML /app/OneClassML/
COPY ./Services/KServe /app/Services/KServe/

ENTRYPOINT python3 Services/KServe/ServeJob.py